### ISSUE TITLE
stud6 not generating correctly

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#41] opened 2020-07-09 17:04 UTC
**Describe the bug**
The generator for stud6 is using 1-4ring2 which is not generated in LDRGenerator.js

**To Reproduce**
- Load a model that uses stud6 (I'm using 30052 from the OMR)
- Generate studs using LDR.Studs.makeGenerators('', 0, 2);
- The error "uncaught exception: Part not loaded: 1-4ring2.dat" is thrown and model loading stops

**Expected behavior**
LDRGenerator.js generates 1-4ring2.
Recommend adding 1-4ring2 to LDR.Generator.map
I'd also recommend auditing the stud generator code since this is the second missing file I've found.

**Device (please complete the following information):**
 - Device/OS: Windows 10
 - Browser: Firefox
 - Version: 68.9.0esr

**Comment by LasseD** [comment] 2020-07-10 12:40
Fixed in latest push to master. This issue was caused by the backupRetrievePartsFromStorage not recursively searching for and loading parts. It has been updated to do this.

Tested with all special stud type, but if you know how to add unit tests, then that would be greatly appreciated.

**Closed** 2020-07-13 09:14 UTC
