### ISSUE TITLE
Does not render well in mobile chrome browsers

### ISSUE THREAD

**Issue by mfeldt** [LasseD/buildinginstructions.js#39] opened 2020-07-03 09:10 UTC
**Describe the bug**

In chrome browsers on mobile devices  rendering and control works badly.  When using an android webview instance, the result is a s the image shown in #28 .   Same actually applies when browsing brickhub.org.

It's a bit of a pity,  since mobile devices are a prime use case for buildinginstructions.js.  Working in webview would be a prerequisite to ever easily make an app from it.

On the upside, it renders  well when using firefox.

**To Reproduce**

Use chrome on any android phone/tablet, go to https://brickhub.org/i/r.php?model=3&color=0
try to navigate and/or rotate/resize the model

Alternatively
  1.) install android studio
  2.) make a simple webview app like so

```java
package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;

public class MainActivity extends AppCompatActivity {


    private WebView myWebView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        myWebView = (WebView) findViewById(R.id.myWebView);
        // Enable Javascript
        WebSettings webSettings = myWebView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webSettings.setPluginState(WebSettings.PluginState.ON);
        webSettings.setAllowFileAccess(true);
        webSettings.setAllowContentAccess(true);
        webSettings.setAllowFileAccessFromFileURLs(true);
        webSettings.setAllowUniversalAccessFromFileURLs(true);
        myWebView.setWebViewClient(new WebViewClient());
        myWebView.loadUrl("https://brickhub.org/i/r.php?model=3&color=0");
    }
}
```

It will look like the screenshot on #28

**Expected behavior**
It would be prefect if it behaved like on a desktop (or mobile in firefox).

**Device (please complete the following information):**
 - android 9

**Comment by LasseD** [comment] 2020-07-16 23:29
Thanks for the bug report and detailed description of how to replicate it.

I have made a fix that works in Android emulators. This has been pushed to the master branch.

I am, however, not satisfied with how the fix has been made. It turns out that the two renderers (the one for the main canvas and the one for the parts list images and previews) affect each other on Android, but not on Desktop and iOS. The issue is with "renderer.setSize()". As soon as I set the size smaller on the secondary renderer, it bounds the rendering area for the main renderer. The fix I have pushed is a hack - it sets a big size on the secondary renderer once icons and previews are rendered/done. Ideally this should not be necessary.

**Comment by LasseD** [comment] 2020-07-17 17:33
Hi @mfeldt . Are you also seeing the issue in the examples that I have set up in the three.js issue?: https://github.com/mrdoob/three.js/issues/19866

**Comment by mfeldt** [comment] 2020-07-23 09:09
Currently I don't Apparently it works in chrome @ android, and I don't manage to ember your result in the emulator...

**Comment by LasseD** [comment] 2020-07-23 21:41
Alright. I will get a more recent Android device than the one that I have (it is from 2012) and see if I can make all pages work properly.

**Comment by LasseD** [comment] 2020-10-16 20:39
Hi @mfeldt . I have purchased the cheapest and slowest Android phone I could find and the page in your example renders correctly in both the chrome browser and the default "Google Go" Android browser.

Can you please confirm that the error still exists?

**Comment by mfeldt** [comment] 2020-10-27 11:51
I confirm it renders well in the browsers.

However, my initial example still leads to a white screen, both in emulation and on the actual phone.  Might be related to webview, though.

**Comment by LasseD** [comment] 2021-08-29 14:52
The issue with WebView is due to WebView not being able to handle multiple canvases correctly. The library uses several canvases in order to draw parts separately.

**Closed by LasseD** 2021-08-29 14:52 UTC
Labels: bug
